[tool.poetry]
name = "bike"
version = "0.1.0"
description = ""
authors = ["Alfio Ferrara <alfio.ferrara@unimi.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyvis = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
